### ISSUE TITLE
Make login text conditional

### ISSUE THREAD

**Issue by finp** [integr8ly/tutorial-web-app#240] opened 2018-11-09 15:27 UTC
At the start of each task, we ask users to log into consoles. This can result in multiple logins. 
The only condition where this makes sense is if they are resuming a session, 
Reword text to take account of this, as discussed with  @soraghallaigh

**Comment by david-martin** [comment] 2018-11-21 10:54
Duplicate of #231

**Closed by david-martin** 2018-11-21 10:54 UTC
