### ISSUE TITLE
Font issues in bottom panel

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#226] opened 2018-11-08 16:27 UTC
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

In the button panel @ the bottom of the content pane: font for completed steps looks like Times New Roman? Looks like the CSS style got messed up

**Comment by mindreeper2420** [comment] 2018-11-08 16:51
This is most likely caused by the text using the Font Awesome font-family, rather than Open Sans.

**Comment by mindreeper2420** [comment] 2018-11-08 19:56
Fixed by #227

**Closed by mindreeper2420** 2018-11-08 19:56 UTC
Labels: bug
