### ISSUE TITLE
Loading screen graphic 'hops' downward

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#215] opened 2018-11-08 16:13 UTC
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

When the loading screen loads, the graphic shifts downward while loading and seems to hop, which doesn't look clean.

**Comment by mindreeper2420** [comment] 2018-11-08 19:57
This is caused by the spacing/alignment being set before the image actually loads into the UI. When slowing down the connection speed, the background image also 'hangs' before appearing. Both can be fixed with this work.

**Closed** 2018-11-09 14:49 UTC
Labels: bug
