### ISSUE TITLE
Asciidoc URLs are styled as code snippets

### ISSUE THREAD

**Issue by mindreeper2420** [integr8ly/tutorial-web-app#161] opened 2018-10-18 14:00 UTC
In various parts of the Task steps, URLs written in asciidoc are being translated to code snippets, but with links inside of them. This is causing the styles to render incorrectly, making them appear as copyable code snippets, rather than clickable links.

**Written as this in the `.adoc`:**
<img width="731" alt="screen shot 2018-10-18 at 9 58 52 am" src="https://user-images.githubusercontent.com/4032718/47159725-801f0000-d2bc-11e8-8a22-4ed285229bb0.png">

**Appears as this in the web app:**
<img width="681" alt="screen shot 2018-10-18 at 9 58 33 am" src="https://user-images.githubusercontent.com/4032718/47159683-65e52200-d2bc-11e8-969d-60f63ef22c55.png">

**Comment by finp** [comment] 2018-10-25 10:30
@mindreeper2420  This format is by design, you copy the url and paste it into a field in the UI.
It is never intended for the user to click these urls.
However, I've noticed two things:
* this should not be a link and it's currently rendering as a link (that can be prevented by `\http://url` syntax
* feedback from testing suggests that all 'copy paste items' should be rendered as copy-able by click
closing this in favor of https://github.com/integr8ly/tutorial-web-app/issues/174

**Closed by finp** 2018-10-25 10:30 UTC
Labels: bug, documentation
