### ISSUE TITLE
When returning to a walkthrough the last step is not correct.

### ISSUE THREAD

**Issue by dlabaj** [integr8ly/tutorial-web-app#179] opened 2018-10-25 20:05 UTC
If you start a walkthrough and return to the home screen after completing the first step, then return to the walkthrough, you will start at the last step completed.  You should start on the step that you are currently working on instead of the last completed step.

**Comment by cgadzinski** [comment] 2018-10-29 02:03
I'll give this a shot if you don't mind

**Comment by david-martin** [comment] 2018-11-21 11:20
Closing as duplicate of #223

**Closed by david-martin** 2018-11-21 11:20 UTC
Labels: bug
